### PR TITLE
Fix building cryptography 3.5

### PR DESCRIPTION
**Pull request by nlewo**

### CODE REVIEW

**Comment by nlewo** [comment]
Since cryptography 3.5.0, Rust is required.

**Comment by nlewo** [comment]
It looks like the CI failure is not related to my change. Could it be related to the latest Nix release?

**Comment by nlewo** [comment]
There are commits fixing CI issues (which i dont really understand:/).

**Comment by lovesegfault** [comment]
If you rebase you can pick-up the CI fixes I landed yesterday

**Comment by nlewo** [comment]
@lovesegfault oh, cool. Thank you!

**Comment by costrouc** [comment]
Checked this PR with trying to build an environment with cryptography 3.5 (that previously failed to build). It now successfully builds with this branch.

**Pull request merged**
