### PR TITLE
feat: Re-enable mypyc from version 0.910

### PR DESCRIPTION
**Pull request by l0b0**
[The latest version builds](https://gitlab.com/victor-engmark/mypy-exercises/-/jobs/1733748482) (search for "Successfully installed mypy-0.910").

### CODE REVIEW

**Comment by NickHu** [comment]
It doesn't build for me unless I disable mypyc, on version 0.910, with the same errors as before.

**Comment by l0b0** [comment]
@NickHu That's weird. Does [this Nix shell](https://gitlab.com/victor-engmark/mypy-exercises/) build for you? I thought by setting my own overrides I wasn't including the default overrides, and it builds with mypy 0.910.

**Comment by cpcloud** [comment]
This is still failing as it was before for me as well.

**Comment by l0b0** [comment]
Dang. What am I doing different since it seems to work with my shell.nix? Maybe someone with more poetry2nix experience can chime in?

**Comment by l0b0** [comment]
In the meantime I've created a revert PR ^.

**Pull request merged**
