### PR TITLE
Nixpkgs backports

### PR DESCRIPTION
**Pull request by purcell**
There seem to have been some changes made to the poetry2nix overrides in nixpkgs over the last 3 months, and I guess we want them here too, in order to have this repo be the ultimate source of truth?

NixOS/nixpkgs@b9b3be8e099f
NixOS/nixpkgs@6b6390885543ee52d0569128648ffefb3d2439b7
NixOS/nixpkgs@253a291274c2790008fe57c97983d3581a2c7798

### CODE REVIEW

**Comment by purcell** [comment]
Alright, so the `wheel` change from downstream fails the tests here. Is this PR misguided? What's the plan for getting updates from here into nixpkgs now? It seems the release numbering scheme changed in June and there haven't been any syncs into nixpkgs from here since then.

**Comment by andersk** [comment]
See also #1291; there was a corresponding update to `python3.pkgs.wheel`, so we need to update our nixpkgs commit at the same time.

**Comment by purcell** [comment]
> so we need to update our nixpkgs commit at the same time.

Oh, I see, you mean the pinned version used in CI here. Makes sense. I'll add a commit here which bumps the flake deps, but I'll leave it to @adisbladis / @cpcloud to suggest how best to coordinate all this.

**Comment by purcell** [comment]
Hmm, if that was indeed the suggestion, it didn't help.

**Comment by cpcloud** [comment]
Closing this out in favor of #1329.

**Pull request closed without merging**
