### PR TITLE
test: Verify Black runtime

### PR DESCRIPTION
**Pull request by l0b0**
Does not trigger #775.

### CODE REVIEW

**Comment by cpcloud** [comment]
@l0b0 Is the idea here to actually trigger #775, or is this to prevent a regression for something that is already fixed elsewhere?

**Comment by l0b0** [comment]
@cpcloud I was hoping to trigger #775, but this should be a valuable regression test nevertheless.

**Comment by cpcloud** [comment]
@l0b0 Does this reproduce if you use `python39` instead of `python3`?

**Comment by l0b0** [comment]
@cpcloud Good call, but it doesn't. At this point, though, I'm moving all my repos to nixpkgs 22.11, which doesn't have this problem.

**Comment by cpcloud** [comment]
Thanks for the PR, but since this isn't reproducing I'm going close it!

**Pull request closed without merging**
