### PR TITLE
Fix mkPoetryPackages: should return deps of deps

### PR DESCRIPTION
**Pull request by sireliah**
This is a fix for [#247 mkPoetryPackages no longer propagates dependencies
](https://github.com/nix-community/poetry2nix/issues/247)

@adisbladis Please take a look and check if this is stable solution!

Important facts:
- I'm doing some string operations on python.pythonVersion to produce right attribute (should look like this: `python37`, `python38`, etc.) and I have no idea if there is better option for that.
- Added tests for current and older version of Python.
- Added documentation how to run tests locally (Tests finish with "Hello, World!" and gunicorn server listening, is this expected?).

### CODE REVIEW

**Comment by sireliah** [comment]
I'll squash the commits once the review is done. :+1:

**Comment by adisbladis** [comment]
> I'm doing some string operations on python.pythonVersion to produce right attribute (should look like this: python37, python38, etc.) and I have no idea if there is better option for that.

Why is this required? This sounds like something that we shouldn't be concerned with.

**Comment by sireliah** [comment]
You're right, that part could have been just `python.pkgs.requiredPythonModules`.

**Comment by adisbladis** [comment]
Thank you! LGTM now :)

**Pull request merged**
