### PR TITLE
Add poetry-core build system for procrastinate

### PR DESCRIPTION
**Pull request by apeschar**

### CODE REVIEW

**Review by l0b0 — APPROVED** [review]
Thanks! Would you also be willing to create tests for this package? If so, see

- `tests/default.nix` for the test entry and
- the `tests/mutmut` directory for a module test or `tests/matplotlib-post-3-7` for a library test.

**Comment by apeschar** [comment]
I've added tests. :)

**Comment by l0b0** [comment]
> I've added tests. :)

Cool, thank you! Once `nixpkgs-fmt` is happy I'll approve it.

**Comment by apeschar** [comment]
Fixed the formatting.

**Review by cpcloud — APPROVED** [review]

**Pull request merged**
