### PR TITLE
chore: bump ruff to 0.5.{0,1}

### PR DESCRIPTION
**Pull request by fpletz**
Tags in the repo are not prefixed with a "v" anymore.

[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [x] There's an _[automated test](tests/default.nix)_ for this change
- [ ] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [x] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

### CODE REVIEW

**Comment by ThoFrank** [comment]
Hey there,
I am trying to build mealie with poetry2nix. And came across this issue:

    error: hash mismatch in fixed-output derivation '/nix/store/15cphqvjp5i29va9gjagfd962g303xgb-source.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-K3wCzwaGOsaiCm2LW4Oc4XOnp6agrdTxCxqEIMq0fuU=

I suspect salsa-macros to be the issue. Adding `"salsa-macros-0.18.0" = "sha256-K3wCzwaGOsaiCm2LW4Oc4XOnp6agrdTxCxqEIMq0fuU=";` for 0.5.1 to getCargoHash helps.
But then I run into another error:

    trace: warning: Unknown watchfiles version: '0.18.1'. Please update getCargoHash.
    error: builder for '/nix/store/yxik3k6hfi5kxwksgcjrjj979zbs1i22-python3.12-coveragepy-lcov-0.1.2.drv' failed with exit code 2;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'poetry'
       >
       >
       For full logs, run 'nix log /nix/store/yxik3k6hfi5kxwksgcjrjj979zbs1i22-python3.12-coveragepy-lcov-0.1.2.drv'.
    error: 1 dependencies of derivation '/nix/store/f0war77h2gc8r9nj0yia596ay744lvbc-python3.12-mealie-1.0.0b.drv' failed to build

Not sure if this error is related or comes from somewhere else.

This is my flake.nix:

    {
      description = "Application packaged using poetry2nix";

      inputs = {
        flake-utils.url = "github:numtide/flake-utils";
        nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";
        poetry2nix = {
          # url = "github:nix-community/poetry2nix";
          url = "github:fpletz/poetry2nix/ruff-0.5.1"; # https://github.com/nix-community/poetry2nix/pull/1725
          # url = "git+file:/home/thomas/src/poetry2nix";
          inputs.nixpkgs.follows = "nixpkgs";
        };

        mealie = {
          url = "github:mealie-recipes/mealie";
          flake = false;
        };
    
      };

      outputs = { self, nixpkgs, flake-utils, poetry2nix, mealie }:
        flake-utils.lib.eachDefaultSystem (system:
          let
            # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
            pkgs = nixpkgs.legacyPackages.${system};
            inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryApplication;
          in
          {
            packages = {
              myapp = mkPoetryApplication { projectDir = mealie; };
              default = self.packages.${system}.myapp;
            };
          });
    }

**Comment by fpletz** [comment]
Thanks for testing! Somehow my changes worked for me. I'll investigate.

**Comment by fpletz** [comment]
> I suspect salsa-macros to be the issue. Adding "salsa-macros-0.18.0" = "sha256-K3wCzwaGOsaiCm2LW4Oc4XOnp6agrdTxCxqEIMq0fuU="; for 0.5.1 to getCargoHash helps.

I see that ruff depends on salsa-macros which lives in the same repo as salsa but I don't need to add a hash to get ruff to evaluate and compile. Even with the current revision of t he `nixos-unstable-small` branch of nixpkgs. Do you maybe use an older revision of nixpkgs?

> Not sure if this error is related or comes from somewhere else.

This is actually unrelated. You need to add an override in your flake to add poetry-core to nativeBuildInputs of coveragepy-lcov or add that to `overrides/build-systems.json` here in poetry2nix.

**Review by adisbladis — APPROVED** [review]

**Comment by ThoFrank** [comment]
Thanks. So it seams the error is now gone. My nixpkgs were only a few days old. No idea what caused it...
And thanks for the tip with the overrides. I was able to get a working build: https://github.com/ThoFrank/mealie-nix

**Pull request merged**
