### PR TITLE
Fix isort override

### PR DESCRIPTION
**Pull request by purcell**
Sorry, I'm an idiot. Fixes mistake in #96.

### CODE REVIEW

**Comment by purcell** [comment]
🙏  Thanks!

**Comment by adisbladis** [comment]
We are all idiots sometimes. Me too for merging ^_^

**Comment by adisbladis** [comment]
Note to self: We need tests for overrides.

**Comment by purcell** [comment]
> We need tests for overrides.

Yep, there's #59. I guess one approach might be to programmatically build a `pyproject.toml` that depends on all the overrides, then lock it and build it. But it might get pretty big and slow.

**Pull request merged**
