### PR TITLE
overrides: add hash for cryptography 42.0.5

### PR DESCRIPTION
**Pull request by gekoke**
```
error: hash mismatch in fixed-output derivation '/nix/store/zy79ajyd8982qs13jmhy5964zyn84s7n-cryptography-42.0.5-vendor.tar.gz.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-Pw3ftpcDMfZr/w6US5fnnyPVsFSB9+BuIKazDocYjTU=
```

### CODE REVIEW

**Comment by neosimsim** [comment]
Had the same result in #1542

**Review by Kiskae — APPROVED** [review]
Can confirm the hash.

**Comment by surajsnair92** [comment]
Hash verified. Can this be merged!

**Comment by gekoke** [comment]
> with this and #1556 unmerged, is there any way to get a poetry2nix-managed project onto a version of cryptography without [a known two-month-old vulnerability](https://github.com/pyca/cryptography/pull/10423)?

I'm just pointing my flake's poetry2nix input to my own fork with the patch applied - can you not do that?

**Comment by cpcloud** [comment]
This is in `master` now.

**Pull request closed without merging**
