### PR TITLE
feat: Make Black installable

### PR DESCRIPTION
**Pull request by l0b0**
Closes https://github.com/nix-community/poetry2nix/issues/375.

### CODE REVIEW

**Comment by cpcloud** [comment]
Should we try to figure out why the parsing fails instead of removing the constraint?

**Comment by cpcloud** [comment]
This should probably also have a test to avoid a regression, if possible.

**Comment by l0b0** [comment]
You're absolutely right @cpcloud. I've just been pushing out PRs to be able to move on from being completely blocked, but I never looked into the underlying issue.

**Comment by adisbladis** [comment]
Closing in favour of #398.

**Pull request closed without merging**
