### PR TITLE
overrides: update build system for pyzmq 26.0.0 to scikit-build

### PR DESCRIPTION
**Pull request by Samuel-Martineau**
Since about two months ago, [`pyzmq` requires `scikit-build` to be built](https://github.com/zeromq/pyzmq/blob/dd3a2537035927779c507a40d94ad5389da75d9c/pyproject.toml#L11). This is a temporary workaround up until #568 is sorted out.

[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [ ] There's an _[automated test](tests/default.nix)_ for this change
- [ ] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [x] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

### CODE REVIEW

**Comment by multun** [comment]
@Samuel-Martineau I'm having the same issue, and had to make the following fixes:
- added scikit-build-core to pyzmq dependencies, which is not the same as scikit-build
- patched scikit-build-core to help it find meson and ninja

```nix
scikit-build-core = super.scikit-build-core.overridePythonAttrs (
  old: {
    preConfigure = ''
      sed -i '/def _get_cmake_path/i def _get_cmake_path(**_): yield Path("${pkgs.cmake}/bin/cmake")
           s/def _get_cmake_path/def _get_cmake_path_old/' src/scikit_build_core/program_search.py
      sed -i '/def _get_ninja_path/i def _get_ninja_path(**_): yield Path("${pkgs.ninja}/bin/ninja")
           s/def _get_ninja_path/def _get_ninja_path_old/' src/scikit_build_core/program_search.py
    '';
    propagatedBuildInputs = (old.propagatedBuildInputs or []) ++ [super.pyproject-metadata super.pathspec];
  }
);
```

Is your PR already in a working state? if so, what nixpkgs channel / pyzmq version did you test it with?

**Comment by Samuel-Martineau** [comment]
@multun If I am frankly honest, I don't recall how I tested this, all that I know is that I managed to get it running somehow. It is therefore quite likely that there are changes that I did that I forgot to include. I will try to test it again from scratch, though I suspect that your work is right and that those changes are indeed needed. If that's the case, would you mind me including your code in this PR?

**Comment by multun** [comment]
Oh yeah help yourself. Let me know if you need review / testing, so far I haven't tested anything.

**Comment by cpcloud** [comment]
Passing locally, merging!

**Pull request merged**
