### PR TITLE
Support orjson 3.9+ by switching to fetching from GitHub and use `Cargo.lock`

### PR DESCRIPTION
**Pull request by Pegasust**
[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [x] There's an _[automated test](tests/default.nix)_ for this change
- [x] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [x] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

Closes https://github.com/nix-community/poetry2nix/issues/1280

---
## Why not continue with Cargo hash?

There are many moving pieces, I speculated that `cargoDeps` + `fetchCargoTarball` fails in some libraries that don't have `Cargo.lock` (common practice to bubble dependencies to applications/libraries), but I'm probably wrong.

Anyways, using `fetchFromGitHub` did the trick!

```
Vendoring libm v0.1.4 (/private/tmp/nix-build-orjson-3.8.12-vendor.tar.gz.drv-0/orjson-3.8.12/cargo-home.VK8/registry/src/index.cr
ates.io-6f17d22bba15001f/libm-0.1.4) to orjson-3.8.12-vendor.tar.gz/libm
error: builder for '/nix/store/2bpspifir8w8ygzhc6rnb4vj1q1xfhll-orjson-3.9.7-vendor.tar.gz.drv' failed with exit code 101;
       last 10 log lines:
       > building
       > error: failed to sync
       >
       > Caused by:
       >   failed to load pkg lockfile
       >
       > Caused by:
       >   no matching package named `ahash` found
       >   location searched: registry `crates-io`
       >   required by package `orjson v3.9.7 (/private/tmp/nix-build-orjson-3.9.7-vendor.tar.gz.drv-0/orjson-3.9.7)`
       For full logs, run 'nix log /nix/store/2bpspifir8w8ygzhc6rnb4vj1q1xfhll-orjson-3.9.7-vendor.tar.gz.drv'.

```

### CODE REVIEW

**Comment by takeda** [comment]
I love the use of `pkgs.rustPlatform.importCargoLock`, but it is there a way to get rid of the git hashes somehow? Seems like we are getting back in square 1 but now git hashes instead of cargo hashes and once again every version has to be added to overrides.

**Comment by Pegasust** [comment]
This is a common [fixed-output derivation (FOD)](https://nixos.org/manual/nix/stable/language/advanced-attributes.html?highlight=outputHash) pattern since `fetchFromGitHub` requires "impurity". I disagree that we're back to square 1 - we're supporting new versions of `orjson` by fetching from `GitHub`. A previous way to do away hashes requires IFD and got closed https://github.com/nix-community/poetry2nix/pull/1371

That said, I could try with `fetchGit` and see how far I can go with it, do note that even if this works, we'd likely still need a version <-> github tag function or mapping, though I do agree this is a lot less confusing than maintaining hashes

**Comment by Pegasust** [comment]
Any interest in merging this, or are we waiting on some CI-maintained mapping for Cargo-related packages?

**Comment by adisbladis** [comment]
I'm waiting on the merge conflict to be resolved.

**Comment by Pegasust** [comment]
Should be up-to-date now!

**Pull request merged**
