### PR TITLE
FAQ: Clarify poetry2nix does not use nixpkgs for Python packages

### PR DESCRIPTION
**Pull request by asymmetric**
I'm sure this could be expanded upon, and maybe this PR can provide the impetus for that.

### CODE REVIEW

**Comment by takeda** [comment]
This is not strictly true. Many packages that aren't explicitly defined in the lock file are actually obtained from nixpkgs.

This mostly applies to overrides, things like when package needs setuptools, flit, poetry, hatch and of course non python dependencies like openssl etc.

**Comment by asymmetric** [comment]
Interesting, I wrote this up after [a comment by @adisbladis](https://github.com/nix-community/poetry2nix/issues/1139#issuecomment-1602268969), but I might've interpreted it too broadly.

But in the end, this was my goal with this PR, to help spell out the architecture so we can document it somewhere visible.

**Comment by takeda** [comment]
I see. The context matters. The question was about package (pillow) listed as a dependency to author's application. In that context pillow defined in poetry is used after applying overrides. The nixpkgs version is totally tossed away.

But then to install pillow poetry2nix adds setuptools dependency: https://github.com/nix-community/poetry2nix/blob/a98ecb470cc4b18407a156e17066173add8e05d3/overrides/build-systems.json#L11369-L11371

That dependency is not defined in poetry.lock file and is pulled from nixpkgs.

You might think "oh this is a special case and it only happens at build time", but then there are broken packages like ansible, where all its dependencies are pulled from nixpkgs because it doesn't define any:

https://github.com/nix-community/poetry2nix/blob/a98ecb470cc4b18407a156e17066173add8e05d3/overrides/default.nix#L111-L129

So the answer to this question is much more complex.

**Comment by asymmetric** [comment]
So a better answer is that everything declared in a `poetry.lock` is built without relying on nixpkgs definitions, with the exception of under-specified packages, like e.g. ansible.

Is this accurate?

**Comment by takeda** [comment]
The thing is that what is clear to me often is not clear to others, but this is what I would write:

> poetry2nix overlays packages taken from `poetry.lock` on top of nixpkgs (in such way that overwritten packages in nixpkgs are completely ignored). Any package that is used, that isn't in the `poetry.lock` file (most commonly build dependencies) is taken from nixpkgs.

**Pull request merged**
