### PR TITLE
botocore-stubs override

### PR DESCRIPTION
**Pull request by takeda**
botocore-stubs override

### CODE REVIEW

**Comment by takeda** [comment]
I'm blanking out how this affects poetry-env build and am not sure how to fix it.

**Comment by RaitoBezarius** [comment]
Could we split the PR to determine the cause?

**Comment by takeda** [comment]
very well, let's try that...

**Comment by takeda** [comment]
@RaitoBezarius done.

Looks like each of the individual PRs succeeded. Perhaps it was a fluke, or there was another change that fixed it.

**Pull request merged**
