### PR TITLE
poetry: 1.1.15 -> 1.2.0

### PR DESCRIPTION
**Pull request by adisbladis**
This contains support for the update Poetry 1.2.0 `pyproject.toml` schema while still retaining backwards compatibility with any older files.

Depends on https://github.com/NixOS/nixpkgs/pull/187999.
Once that + the backport are in released channels this PR will be merged.

----

Closes https://github.com/nix-community/poetry2nix/issues/681

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code looks good.

**Comment by Smaug123** [comment]
@adisbladis Per https://nixpk.gs/pr-tracker.html?pr=187999 the nixpkgs PR is now in nixos-unstable; per https://nixpk.gs/pr-tracker.html?pr=189283 the backport is in nixos-22.05. How's it looking for this PR?

**Comment by cpcloud** [comment]
Well, time to try this out again!

**Comment by cpcloud** [comment]
It looks like `geopandas` and `ipdb` are two packages that cannot be installed with poetry2nix due to an infinite recursion error, which appears to be because they both depend on `setuptools` as `install_requires` (runtime) dependencies.

I've actually had two PRs open for a bit on both of these projects to fix the issue (https://github.com/gotcha/ipdb/pull/254 and https://github.com/Toblerity/Fiona/pull/1139).

We were using `ipdb` in ibis as a development dependency, but now we're not because of that issue and we have `geopandas` which depends on `Fiona` as an optional dependency for geospatial functionality.

What's interesting is that the Fiona issue doesn't show up with `poetry < 1.2`.

Is there any way we can work around this issue in `poetry2nix`? Happy to open a PR, but not entirely sure where to start poking around.

**Comment by cpcloud** [comment]
Another package that fails is `poetry-dynamic-versioning` with the same infinite recursion error, but I believe a different cycle. In `ipdb` and `geopandas` the cycle is between setuptools-scm and setuptools, where as here I believe the cycle is between poetry-dynamic-versioning and poetry (though I'm not 100% sure about that).

**Pull request merged**
