### PR TITLE
gitignore: ignore direnv

### PR DESCRIPTION
**Pull request by cpcloud**
This PR adds `.direnv` to the repository `.gitignore` file.

### CODE REVIEW

**Comment by adisbladis** [comment]
What is creating this file? Why should we ignore it?

**Comment by cpcloud** [comment]
Ah, sorry I should've given a bit more context. This file is created by the direnv tool, kicked off by running `direnv allow` in a directory with an `.envrc` such as a clone of this repo.

It should be ignored for a variety of reasons, but I think probably the one that sticks out to me the most is that its not meant to be shared with anyone.

**Comment by adisbladis** [comment]
This file is _not_ created by direnv but by https://github.com/nix-community/nix-direnv/.
Regardless, this change seems sensible.

Could you add a reference to https://github.com/nix-community/nix-direnv/ in your commit message?

**Comment by cpcloud** [comment]
@adisbladis Thanks! Will do.

**Comment by cpcloud** [comment]
@adisbladis Done! Thanks again for the review.

**Pull request merged**
