### PR TITLE
overrides: add hashes for current ruff versions

### PR DESCRIPTION
**Pull request by fpletz**
[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [x] There's an _[automated test](tests/default.nix)_ for this change
- [ ] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [ ] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

### CODE REVIEW

**Comment by 9999years** [comment]
Anything blocking this? 

@adisbladis Is more maintainer bandwidth needed?

**Comment by fpletz** [comment]
Rebased onto current master.

The test suite is flaky. Every version bump has an accompanying bump in the ruff test and the ruff test for every commit has always been green.

**Comment by cpcloud** [comment]
Which test suite is flaky?

The poetry2nix test suite is a bit flaky right now because I am merging things before waiting for the formatting job to finish. Other than that it's pretty reliable.

**Comment by cpcloud** [comment]
Passing locally on:

- x86_64-darwin
- aarch64-darwin
- x86_64-linux

Merging!

**Pull request merged**
