### PR TITLE
improving flake experience

### PR DESCRIPTION
**Pull request by teto**
I've been experimenting with flakes.

### CODE REVIEW

**Comment by adisbladis** [comment]
I don't think there is any point in poetry2nix adding a `flake.lock`.

**Comment by teto** [comment]
what about removing 'edition' xD (I can drop the lock commit) ?

**Comment by adisbladis** [comment]
Removing `edition` is a :+1:.

> I can drop the lock commit

Please do.

**Comment by teto** [comment]
done

**Pull request merged**
