### PR TITLE
poetry: 1.3.2 -> 1.5.1

### LINKED ISSUE #1217: Old version of poetry
The commit says we should have version 1.3.2:

https://github.com/nix-community/poetry2nix/commit/ce5d417de0a07a9007a359b7b3f7b6c984ab204b

But it looks like we only have 1.3.0:

$ poetry -V
Poetry (version 1.3.0)

$ which poetry
/nix/store/z6s4c81inn8s91fik8iahxlfccnz5agj-python3.10-poetry-1.3.2/bin/poetry

In actual fact version 1.5.1 is now available: https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by Dessix**
Updates Poetry to 1.5.1, preventing breakage on newer Poetry syntax around explicit dependency sources, and takes on changes from the newer poetry-core solver to provide better multi-platform solutions with smaller lockfiles.  

Fixes #1217.

### CODE REVIEW

**Comment by Dessix** [comment]
Bah, accidentally pushed to the wrong branch. Disregard the 1.6 bump, force-pushing back to 1.5.1.

**Comment by Dessix** [comment]
I'm not entirely sure, but it looks like the Darwin checks failed simply because it tried to rebuild every python package based on poetry2nix simultaneously. The fact that it got 6 hours into it seems promising, though.
Anyone familiar enough with it to check?

**Comment by andronat** [comment]
Any updates on this?

**Comment by Dessix** [comment]
> Any updates on this?

@adisbladis is backlogged a bit, but spoke with me a few days ago that this is likely to be reviewed soon.

**Comment by cpcloud** [comment]
See https://github.com/nix-community/poetry2nix/pull/1303, I've bumped the version to 1.6.1

**Comment by cpcloud** [comment]
Superseded by #1303

**Pull request closed without merging**
