### PR TITLE
overrides: discord-py

### PR DESCRIPTION
**Pull request by ProducerMatt**
This package doesn't build without setuptools.

### CODE REVIEW

**Comment by adisbladis** [comment]
Could you add it via the JSON file as we do with other setuptools packages?

**Comment by ProducerMatt** [comment]
@adisbladis done, sorry I missed that.

**Comment by ProducerMatt** [comment]
I see there's already an override for `discordpy`, but I had to override `discord-py`, wonder why

**Comment by ProducerMatt** [comment]
What's with the build failure? Is there a problem?

**Comment by adisbladis** [comment]
> What's with the build failure? Is there a problem?

To reduce merge conflicts we require the build systems to be sorted.
This can be done with this one-liner:
`jq --raw-output --sort-keys < overrides/build-systems.json | sponge overrides/build-systems.json`

**Pull request merged**
