### PR TITLE
added overrides but theyre not sorted :(

### PR DESCRIPTION
**Pull request by super-secret-github-user**

### CODE REVIEW

**Comment by cpcloud** [comment]
@super-secret-github-user Any reason you're not able to sort them?

**Comment by super-secret-github-user** [comment]
kp900 on the matrix said there was a script I had to run but that errors out:
```

**Comment by super-secret-github-user** [comment]
also when I try to use this fork to build a nix shell the overrides dont seem to be picked up. not sure if the script is responsible for making sure they get picked up

**Comment by super-secret-github-user** [comment]
What needs to be done here before this is accepted?

**Comment by l0b0** [comment]
You can sort the file like [this](https://github.com/nix-community/poetry2nix/pull/843#issue-1477339099): `jq --raw-output --sort-keys < build-systems.json > new.json && mv new.json build-systems.json`

**Comment by super-secret-github-user** [comment]
please let me know what else is outstanding on this. If adding the sorting step to CI is a pain then I suggest just dropping a line in the edgecases doc to outline how to upstream overrides in the future.

**Review by l0b0 — APPROVED** [review]

**Comment by l0b0** [comment]
Probably nothing else is outstanding, but I think the maintainers are busy.

**Comment by super-secret-github-user** [comment]
pinging @cpcloud

**Pull request merged**
