### PR TITLE
pyqt6 override

### LINKED ISSUE #1191: pyside6
Can I use __poetry2nix__ with __pyside6__?

It looks like __pyqt5__ has special overrides.

https://github.com/nix-community/poetry2nix/blob/4f91d45e39cf64b642c6d2725c7bd50d6fcb544b/overrides/default.nix#L2133-L2149

Would I have to write a simliar override?

Here is __pyside6__ in __nixpkgs__:

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/python-modules/pyside6/default.nix

### PR DESCRIPTION
**Pull request by considerate**
[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [x] There's an _[automated test](tests/default.nix)_ for this change
- [ ] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [x] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

Fixes #1191

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]
Assuming this passes CI, LGTM.

**Comment by considerate** [comment]
It's not clear to me why pyqt6 failed to compile now. I'll test a bit locally. I hope it's not down to an update of the nixpkgs version and that it's really sensitive to the version of `qt6` in nixpkgs.

**Comment by considerate** [comment]
It looks like my hunch was correct. This is caused by a mismatch between the `qt6` version from `nixpkgs` and `pyqt6`. On further inspection I think that it's better to use the libraries from the `pyqt6-qt6` package when building `pyqt6`. However, I can't seem to make that work out.


I attempt to get this working is [here](https://github.com/considerate/poetry2nix/commit/0215dbfb50ecd6d5ac3a723b3608584dd04bf8df)

**Comment by considerate** [comment]
Interestingly why the [description of the pyqt6-qt6 package](https://pypi.org/project/PyQt6-Qt6/) states:

> This package contains the subset of a Qt installation that is required by PyQt6.
 
There are libraries in wheel that try to link against libraries named `libQt6*` that aren't present in the wheel itself.

**Review by cpcloud — APPROVED** [review]
Sweet!

Assuming the mac tests pass, this LGTM!

**Comment by cpcloud** [comment]
@considerate can you add `Fixes #1191` to your PR description? It looks like this PR adds support for PySide 6 🎉

**Comment by considerate** [comment]
@cpcloud: @adisbladis beat me to it.

**Pull request merged**
